services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: yoismak/quiz-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=quiz_backend_1
      - BACKEND_PORT=3001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yoismak/quiz-backend:latest
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
