services:
  frontend:
    environment:
      - VITE_BACKEND_URI=localhost
      - VITE_BACKEND_PORT=3001
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/quiz
      - JWT_SECRET=somejwtsecret
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network: